# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy.
FROM node:24-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public && npm run build

FROM node:24-alpine AS runner
WORKDIR /app
# node:*-alpine ships a 'node' user at uid 1000 — reuse it instead of
# creating a duplicate (adduser would fail with uid conflict).
RUN apk add --no-cache tini
ENV NODE_ENV=production PORT=3000
COPY --from=builder --chown=node:node /app/.next ./.next
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/package*.json ./
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
USER node
EXPOSE 3000
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npx", "next", "start", "-p", "3000"]
